name: Build LaTeX document
on:
  push:
      branches: [ "master" ]
  pull_request:
      branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex
          root_file: template.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: tex/template.pdf
          
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - uses: docker://pandoc/core:2.9
        with:
          # allows you to break string into multiple lines
          args: >-
            pandoc
            ./tex/template.tex
            -f latex+raw_tex
            -t docx
            -o output/template.docx
      - uses: actions/upload-artifact@v3
        with:
          name: docx_version
          path: output
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: build
          force_orphan: true

# args: >-
#             -s comutation-manuscript.tex # The s flag stands for standalone and it takes the name of the 
#             -f latex # FROM LaTeX
#             -t docx  # TO docx
#             -o output/comutation-manuscript.docx # The output file path
#             --bibliography reference_files/references.bib # The .bib citation files to use. Each use of the --bibliography flag adds another file that pandoc will use.
#             --bibliography reference_files/R_citations.bib 
#             --bibliography reference_files/additional_citations.bib 
#             --csl nature-genetics.csl  # The Citation Style Language (CSL) file with information on how to create the citations and bibliography. Others can be found at this GitHub repository or downloaded from Zotero.
#                   https://github.com/citation-style-language/styles
#                   https://www.zotero.org/styles?q=nature