name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex
          root_file: template.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: tex/template.pdf
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - uses: docker://pandoc/core:2.9
        with:
          # allows you to break string into multiple lines
          args: >-
            -s ./tex/template.tex 
            -f latex 
            -t docx 
            -o output/template.docx 
      - uses: actions/upload-artifact@v3
        with:
          name: manuscript
          path: output
